// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("BatchDetail")]
    public partial class BatchDetail
    {
        [Key]
        public int BatchDetailId { get; set; }
        public int? BatchControlId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string RecordType { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string PayerAbbreviation { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string PayerName { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string PayerAddress1 { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string PayerAddress2 { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string PayerAddress3 { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string PostCode { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PayerAccountNo { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string PayerTaxID { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string PayerSocialSecurity { get; set; }
        [StringLength(8)]
        [Unicode(false)]
        public string EffectiveDate { get; set; }
        [StringLength(35)]
        [Unicode(false)]
        public string BatchNo { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string FileBatchNoBankReference { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PaymentRefNo1 { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PaymentRefNo2 { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PaymentRefNo3 { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string SupplierRefNo { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string PayType { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string PayeeName { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string PayeeIdCardNo { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string PayeeAddress1 { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string PayeeAddress2 { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string PayeeAddress3 { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string PostCodeD { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string PayeeBankCode { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string PayeeBankAccountNo { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string InvoiceAmount { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TotalVATAmount { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string VATPercent { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TotalWHTAmount { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TotalTaxableAmount { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TotalDiscountAmount { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string NetChequeTransferAmount { get; set; }
        [StringLength(2)]
        [Unicode(false)]
        public string DeliveryMethod { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string PickUpChequeLocation { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string ChequeNumber { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string ChequeStatus { get; set; }
        [StringLength(8)]
        [Unicode(false)]
        public string ChequeStatusDate { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string NotificationMethod { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string MobileNumber { get; set; }
        [StringLength(70)]
        [Unicode(false)]
        public string EmailAddress { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string FaxNumber { get; set; }
        [StringLength(8)]
        [Unicode(false)]
        public string DateReturnChequeToCompany { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string ReturnChequeMethod { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string StrikethroughFlag { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string AccountPayeeOnlyFlag { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string AcknowledgementDocumentNotify { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string PrintLocation { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string KTBRef { get; set; }
        [StringLength(151)]
        [Unicode(false)]
        public string ForKTBSystem { get; set; }
        [StringLength(350)]
        [Unicode(false)]
        public string FreeFiller { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string TotalPaymentRecord { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TotalPaymentAmount { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string TotalWHTRecord { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string TotalInvoiceRecord { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TotalInvoiceNetAmount { get; set; }
        [StringLength(15)]
        [Unicode(false)]
        public string TotalMailRecord { get; set; }
        [StringLength(25)]
        [Unicode(false)]
        public string FileBatchReference { get; set; }
        [StringLength(1317)]
        [Unicode(false)]
        public string Filler { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string CarriageReturn { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string EndOfLine { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string DataType { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}