// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DemoPOS.Models
{
    [Table("BatchControl")]
    public partial class BatchControl
    {
        [Key]
        public int BatchControlId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string BatchControlCode { get; set; }
        public int? ItemCount { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}