// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("Detail")]
    public partial class Detail
    {
        [Key]
        public int DetailId { get; set; }
        public int? BatchControlId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string AppId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string ClaimNo { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Prefix { get; set; }
        /// <summary>
        /// วันทีพิมพ์บนหน้าเช็ค
        /// </summary>
        [StringLength(8)]
        [Unicode(false)]
        public string ChequeEffectiveDate { get; set; }
        /// <summary>
        /// หมายเลขเช็ค
        /// </summary>
        [StringLength(10)]
        [Unicode(false)]
        public string ChequeNumber { get; set; }
        /// <summary>
        /// ชื่อผู้รับเช็ค
        /// </summary>
        [StringLength(100)]
        [Unicode(false)]
        public string PayeeName { get; set; }
        /// <summary>
        /// จำนวนเงินหักภาษี ณ ที่จ่าย
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string WithholdingTaxAmount { get; set; }
        /// <summary>
        /// จำนวนเงินจ่ายสุทธิ (ตามเช็ค)
        /// </summary>
        [StringLength(20)]
        [Unicode(false)]
        public string NetCheque { get; set; }
        /// <summary>
        /// สถานะของเช็ค 
        /// I :   Issue  ออกเช็คแล้ว 
        /// D :   Deliver  รับเช็คแล้ว 
        /// P :   Paid  เช็คเรียกเก็บแล้ว 
        /// R :   Return ส่งเช็คคืนบริษัท 
        /// S :   Stop  อายัดเช็ค 
        /// C :   Canceled  ยกเลิกเช็ค
        /// </summary>
        [StringLength(5)]
        [Unicode(false)]
        public string ChequeStatus { get; set; }
        /// <summary>
        /// วันที่สถานะเช็คเปลี่ยนแปลง
        /// </summary>
        [StringLength(8)]
        [Unicode(false)]
        public string TransactionDate { get; set; }
        /// <summary>
        /// วันทีพิมพ์เช็ค
        /// </summary>
        [StringLength(8)]
        [Unicode(false)]
        public string OutwardDate { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }

        [ForeignKey("BatchControlId")]
        [InverseProperty("Details")]
        public virtual BatchControl BatchControl { get; set; }
    }
}