// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SMIXKTBConvenienceCheque.Models
{
    [Table("Detail")]
    public partial class Detail
    {
        [Key]
        public int DetailId { get; set; }
        public int? BatchControlId { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string AppId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string ClaimNo { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Prefix { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}